export const classCategories = {
    physics: [
        "SI Physics",
        "Physics: Sound and Light",
        "Physics C: Mechanics",
        "Physics C: Electricity/Magnetism",
        "Planetary Science",
        "Modern Physics",
        "Computational Science",
    ],
    chem: [
        "SI Chemistry",
        "Advanced Chemistry - Structure and Properties",
        "Advanced Chemistry - Chemical Reactions",
        "The Physical Chemistry of Materials",
        "Organic Chemistry I",
        "Organic Chemistry II",
        "Biochemistry",
        "Environmental Chemistry",
        "Medicinal Chemistry",
    ],
    biology: [
        "Biology: Evolution & Environment",
        "Biology: Molecular & Cellular",
        "Evolution, Biodiversity, and Ecology",
        "Cancer Biology",
        "Environmental Microbiology",
        "Pathophysiology",
        "Biology of Behavior",
    ],
    sciother: [
        "MSI",
        "Electronics",
        "Engineering",
        "Engineering: Statics & Dynamics",
    ],
    mathother: [
        "Introduction to Proofs",
        "Modern Geometries",
        "Statistical Exploration and Description",
        "Statistical Experimentation and Inference",
        "Number Theory",
        "Discrete Mathematics",
        "Multi-Variable Calculus",
        "Theory of Analysis",
        "Differential Equations",
        "Linear Algebra",
        "Abstract Algebra",
    ],
    mathcore: [
        "Geometry",
        "MI I/II",
        "MI II",
        "MI III",
        "MI IV",
        "AB I",
        "AB II",
        "BC I",
        "BC II",
        "BC III",
        "BC I/II",
        "BC II/III",
    ],
    cs: [
        "CSI",
        "OOP",
        "Web Technologies",
        "Advanced Programming",
        "Microcontroller Applications (CS)",
        "CS Seminar: Android Apps Development",
        "CS Seminar: Linux and Cybersecurity",
        "CS Seminar: Machine Learning",
    ],
    language: [
        "French I",
        "French II",
        "French III",
        "French IV",
        "French V",
        "Spanish II",
        "Spanish III",
        "Spanish IV",
        "Spanish V",
        "German I",
        "German II",
        "German III",
        "Mandarin Chinese I",
        "Mandarin Chinese II",
        "Mandarin Chinese III",
    ],
};
